# This workflow checks Code Quality for API
name: Code Quality

# Controls when the workflow will run
on: # yamllint disable-line rule:truthy
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Cancels previous runs in PR branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow performs a lint check on the code
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      # Caches dependencies
      - name: Cache Node Modules
        id: cache 
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      # Run Lint check
      - name: Lint Check
        uses: tj-actions/eslint-changed-files@v25
        with:
          skip_annotations: "true"
          config_path: "eslint.config.js"
          file_extensions: |
            **/*.js
      